[build]
  publish = "."
  command = ""

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=60"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=60"

[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

[[headers]]
  for = "/pages/*.html"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
